# Generated by Django 3.2.19 on 2023-08-21 11:53

import uuid

import django.db.models.deletion
import django_extensions.db.fields
import utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("groups", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from=("name",), unique=True
                    ),
                ),
                ("public_name", models.CharField(max_length=255)),
                ("description_private", models.TextField(blank=True, null=True)),
                ("description_public", models.TextField(blank=True, null=True)),
                ("is_public_accessible", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("meta", utils.fields.DictJSONField(default=dict)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="categories",
                        to="groups.group",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
