repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key
  -   repo: https://github.com/humitos/mirrors-autoflake.git
      rev: v1.1
      hooks:
      - id: autoflake
        args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']
  -   repo: https://github.com/timothycrosley/isort
      rev: '5.13.2'
      hooks:
      - id: isort
  -   repo: https://github.com/ambv/black
      rev: '23.10.1'
      hooks:
      - id: black
        language_version: python3
  -   repo: https://github.com/pycqa/flake8
      rev: '6.1.0'
      hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.3"
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.0.3
        files: '\.(js|ts|jsx|tsx|scss|css)$'
  - repo: https://github.com/djlint/djLint
    rev: v1.34.1
    hooks:
      - id: djlint-reformat-django
      - id: djlint-django
        args: ["--ignore", "H006,H013,H023"]
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.56.0'
    hooks:
    -   id: eslint
        additional_dependencies:
        - eslint@8.57.0
        - eslint-config-prettier@9.1.0
        - eslint-plugin-prettier@5.1.3
