version: '3'
services:
  gateway:
    container_name: onderwerpen.mor.local
    build: ./nginx
    volumes:
      - ./nginx/nginx-default.development.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      onderwerpen_app:
        condition: service_started
    ports:
      - 8006:8006
    networks:
      - mor_bridge_network
    env_file:
      - .env.local

  onderwerpen_app:
    build: ./app
    env_file:
      - .env.local
    volumes:
      - ./app:/app
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - onderwerpen_network
      - mor_bridge_network
    command: ["bash", "/app/deploy/docker-entrypoint.development.sh"]
    restart: always

  database:
    image: postgis/postgis:11-3.3
    shm_size: '1024m'
    ports:
      - "5432"
    env_file:
      - .env.local
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - onderwerpen_network

  redis:
    image: redis
    networks:
      - onderwerpen_network
    ports:
      - "6379"

volumes:
  postgres-data:

networks:
  onderwerpen_network:
    external: true
  mor_bridge_network:
    external: true
