version: '3'
services:
  gateway:
    container_name: onderwerpen.mor.local
    build: ./nginx
    volumes:
      - ./nginx/nginx-default.development.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      onderwerpen_app:
        condition: service_started
    ports:
      - 8006:8006
    networks:
      - mor_network
    env_file:
      - .env.local

  onderwerpen_app:
    build: ./app
    ports:
      - "8000"
    env_file:
      - .env.local
    depends_on:
      database:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - mor_network

  database:
    image: postgis/postgis:11-3.3
    shm_size: '1024m'
    ports:
      - "5432"
    env_file:
      - .env.local
    networks:
      - mor_network

  redis:
    image: redis
    networks:
      - mor_network
    ports:
      - "6379"

  app_celery_worker:
    build: ./app
    container_name: onderwerpen_celery_worker
    command: "celery -A config worker -l info"
    depends_on:
      database:
        condition: service_started
      redis:
        condition: service_started
    env_file:
      - .env.local
    networks:
      - mor_network

  app_celery_beat:
    build: ./app
    container_name: onderwerpen_celery_beat
    command: "celery -A config beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    depends_on:
      database:
        condition: service_started
      redis:
        condition: service_started
    env_file:
      - .env.local
    networks:
      - mor_network

volumes:
  postgres-data:

networks:
  mor_network:
    external: true
