version: '3'
services:
  app:
    build: ./app
    ports:
      - "8006:8000"
    env_file:
      - .env.test
    depends_on:
      redis:
        condition: service_started
      database:
        condition: service_started
    networks:
      - onderwerpen_network

  database:
    image: postgis/postgis:16-3.4
    shm_size: '1024m'
    ports:
      - "5432"
    env_file:
      - .env.test
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - onderwerpen_network

  redis:
    image: redis
    networks:
      - onderwerpen_network
    ports:
      - "6379"

networks:
  onderwerpen_network:
    external: true
