# Generated by Django 3.2.19 on 2023-08-21 11:53

import uuid

import django.db.models.deletion
import utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sort", models.IntegerField(default=0)),
                ("key", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("public_name", models.CharField(max_length=255)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("long-text", "Long text"),
                            ("integer", "Integer"),
                            ("number", "Number"),
                            ("bool", "Bool"),
                        ],
                        default="text",
                        max_length=125,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("required", models.BooleanField(default=True)),
                ("meta", utils.fields.DictJSONField(default=dict)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="categories.category",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
