# Generated by Django 3.2.19 on 2023-08-21 11:53

import uuid

import django_extensions.db.fields
import utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from=("name",), unique=True
                    ),
                ),
                ("public_name", models.CharField(max_length=255)),
                ("is_public_accessible", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("meta", utils.fields.DictJSONField(default=dict)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
