name: "Deploy to Test"

on:
  push:
    branches:
      - develop

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    uses: ./.github/workflows/build-deploy.yaml
    with:
      environment_name: test
      image_tag: on-test
    secrets: inherit
