name: "Deploy to Prod"

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    uses: ./.github/workflows/build-deploy.yaml
    with:
      environment_name: prod
      image_tag: on-prod
    secrets: inherit
